name: Publish Cloudflare Worker

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run publish
        env:
          CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}